
name: CI/CD with Docker

on:
  push:
    branches: [ "master-test" ] # master 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/travel:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/travel:latest

    # 4. EC2 접속 및 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 기존 컨테이너 중지 및 삭제
          docker stop travel || true
          docker rm travel || true
          # 최신 이미지 풀
          docker pull ${{ secrets.DOCKER_USERNAME }}/travel:latest
          # 새 컨테이너 실행
          # docker run -d -p 80:8080 --name travel ${{ secrets.DOCKER_USERNAME }}/travel:latest
          docker run -d \
            -p 80:8080 \
            -v /home/uploads:/home/uploads \
            --name travel \
            -e DB_URL="${{ secrets.EC2_HOST }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/travel:latest
          # 미사용 이미지 삭제 (용량 확보)
          docker image prune -f
